# Setup
title:        Personal Blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Prashast Mehra
  url:        https://imprashast.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown