# Setup
title:        Das Bin Ich
tagline:      Rants, Motivation and Quotes from a Full Stack Developer
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Prashast Mehra
  url:        https://imprashast.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown